# Generated by Django 5.2.9 on 2025-12-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_profile_is_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
